#
# Copyright (c) 2019-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

replicaCount: 1

labels:
  job:
    node_selector_key: node-role.kubernetes.io/control-plane
    node_selector_value: ""

name: ceph-pools-audit
ceph_client:
  configmap: ceph-etc-pools-audit

conf:
  ceph:
    storage_tiers:
    - name: ceph-store
      replication: 2
      min_replication: 1
      crush_ruleset: storage_tier_ruleset
    monitors: []

images:
  tags:
    ceph_config_helper: docker.io/openstackhelm/ceph-config-helper:ubuntu_focal-20230424
  pullPolicy: "IfNotPresent"
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry

jobs:
  job_ceph_pools_audit:
    cron: "*/5 * * * *"
    startingDeadlineSeconds: 200
    history:
      success: 3
      failed: 1

resources: {}

nodeSelector: { node-role.kubernetes.io/control-plane: "" }

tolerations: []

affinity: {}

manifests:
  job_ceph_pools_audit: true
  configmap_bin: true
  configmap_ceph_conf: true
