{{/*
#
# Copyright (c) 2020 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{ $defaults := .Values.classdefaults }}
{{ $provisioner := .Values.global.provisioner_name }}
{{ $defaultSC := .Values.global.defaultStorageClass }}
{{- range $classConfig := .Values.classes }}

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  {{- if eq $defaultSC $classConfig.name}}
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
  {{- end }}
  name: {{ $classConfig.name }}
provisioner: {{  $provisioner }}
parameters:
    monitors: "{{ $monitors := or $classConfig.monitors $defaults.monitors }}{{ join "," $monitors}}"
    adminId: {{ or $classConfig.adminId $defaults.adminId }}
    adminSecretName: {{ or $classConfig.adminSecretName $defaults.adminSecretName }}
    adminSecretNamespace:  {{ or $classConfig.adminSecretNamespace $defaults.adminSecretNamespace }}
    claimRoot: {{ $classConfig.claim_root }}
---
{{- end }}