{{/*
#
# Copyright (c) 2018-2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.global.provisionStorageClass }}
{{ $namespace := .Release.Namespace }}
{{ $defaults := .Values.classdefaults}}
{{ $provisioner := .Values.global.provisioner_name }}
{{ $defaultSC := .Values.global.defaultStorageClass }}
{{- range $classConfig := .Values.classes }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    {{- if eq $defaultSC $classConfig.name}}
    annotations:
        "storageclass.kubernetes.io/is-default-class": "true"
        "helm.sh/hook": "pre-upgrade, pre-install"
        "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- end }}
    name: {{ $classConfig.name }}
provisioner: {{ $provisioner }}
parameters:
    monitors: "{{ $monitors := or $classConfig.monitors $defaults.monitors }}{{ join "," $monitors}}"
    adminId: {{ or $classConfig.adminId $defaults.adminId}}
    adminSecretName: {{ or $classConfig.adminSecretName $defaults.adminSecretName }}
    adminSecretNamespace: {{ $namespace }}
    pool: {{ or $classConfig.pool_name $defaults.pool_name }}
    userId: {{ or $classConfig.userId $defaults.userId }}
    userSecretName: {{ $classConfig.userSecretName }}
    imageFormat: {{ or $classConfig.imageFormat $defaults.imageFormat | quote }}
    imageFeatures: {{ or $classConfig.imageFeatures $defaults.imageFeatures}}
mountOptions:
- discard
---
{{- end }}
{{- end }}
