#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: ceph-pools-audit
  labels:
    chart_group: starlingx-ceph-charts
spec:
  releaseName: stx-ceph-pools-audit
  chart:
    spec:
      chart: ceph-pools-audit
      version: REPLACE_HELM_CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: ceph-pools-audit-static-overrides
      valuesKey: ceph-pools-audit-static-overrides.yaml
    - kind: Secret
      name: ceph-pools-audit-system-overrides
      valuesKey: ceph-pools-audit-system-overrides.yaml
